version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: UTC
    open-pull-requests-limit: 5
    groups:
      dev-deps:
        dependency-type: development
        update-types:
          - minor
          - patch
      prod-deps:
        dependency-type: production
        update-types:
          - patch
    commit-message:
      prefix: "chore(deps)"
      prefix-development: "chore(dev-deps)"
    labels:
      - dependencies

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: UTC
    commit-message:
      prefix: "chore(actions)"
    labels:
      - dependencies
      - ci
